package Entidad;

import java.io.Serializable;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class F47011 implements Serializable {

    private static final long serialVersionUID = 1L;

    private String SYEDTY;
    private String SYEDSQ;
    private String SYEKCO;
    private String SYEDOC;
    private String SYEDCT;
    private String SYEDLN;
    private String SYEDST;
    private String SYEDFT;
    private String SYEDDT;
    private String SYEDER;
    private String SYEDDL;
    private String SYEDSP;
    private String SYEDBT;
    private String SYPNID;
    private String SYOFRQ;
    private String SYNXDJ;
    private String SYSSDJ;
    private String SYTPUR;
    private String SYKCOO;
    private String SYDOCO;
    private String SYDCTO;
    private String SYSFXO;
    private String SYMCU;
    private String SYCO;
    private String SYOKCO;
    private String SYOORN;
    private String SYOCTO;
    private String SYRKCO;
    private String SYRORN;
    private String SYRCTO;
    private String SYAN8;
    private String SYSHAN;
    private String SYPA8;
    private String SYDRQJ;
    private String SYTRDJ;
    private String SYPDDJ;
    private String SYOPDJ;
    private String SYADDJ;
    private String SYCNDJ;
    private String SYPEFJ;
    private String SYPPDJ;
    private String SYPSDJ;
    private String SYVR01;
    private String SYVR02;
    private String SYDEL1;
    private String SYDEL2;
    private String SYINMG;
    private String SYPTC;
    private String SYRYIN;
    private String SYASN;
    private String SYPRGP;
    private String SYTRDC;
    private String SYPCRT;
    private String SYTXA1;
    private String SYEXR1;
    private String SYTXCT;
    private String SYATXT;
    private String SYPRIO;
    private String SYBACK;
    private String SYSBAL;
    private String SYNTR;
    private String SYANBY;
    private String SYCARS;
    private String SYMOT;
    private String SYCOT;
    private String SYROUT;
    private String SYSTOP;
    private String SYZON;
    private String SYCNID;
    private String SYFRTH;
    private String SYAFT;
    private String SYRCD;
    private String SYOTOT;
    private String SYTOTC;
    private String SYWUMD;
    private String SYVUMD;
    private String SYAUTN;
    private String SYCACT;
    private String SYCEXP;
    private String SYCRMD;
    private String SYCRRM;
    private String SYCRCD;
    private String SYCRR;
    private String SYLNGP;
    private String SYFAP;
    private String SYFCST;
    private String SYORBY;
    private String SYTKBY;
    private String SYURCD;
    private String SYURDT;
    private String SYURAT;
    private String SYURAB;
    private String SYURRF;
    private String SYTORG;
    private String SYUSER;
    private String SYPID;
    private String SYJOBN;
    private String SYUPMJ;
    private String SYTDAY;
    private String SYIR01;
    private String SYIR02;
    private String SYIR03;
    private String SYIR04;
    private String SYIR05;
    private String SYVR03;
    private String SYSOOR;
    private String SYPMDT;
    private String SYRSDT;
    private String SYRQSJ;
    private String SYPSTM;
    private String SYPDTT;
    private String SYOPTT;
    private String SYDRQT;
    private String SYADTM;
    private String SYADLJ;
    private String SYPBAN;
    private String SYITAN;
    private String SYFTAN;
    private String SYDVAN;
    private String SYDOC1;
    private String SYDCT4;
    private String SYCORD;
    private String SYBSC;
    private String SYBCRC;
    private String SYRSHT;
    private String SYHOLD;
    private String SYFUF1;
    private String SYAUFT;
    private String SYAUFI;
    private String SYOPBO;
    private String SYOPTC;
    private String SYOPLD;
    private String SYOPBK;
    private String SYOPSB;
    private String SYOPPS;
    private String SYOPPL;
    private String SYOPMS;
    private String SYOPSS;
    private String SYOPBA;
    private String SYOPLL;
    private String SYPRAN8;
    private String SYPRCIDLN;
    private String SYOPPID;
    private String SYCCIDLN;
    private String SYSDATTN;
    private String SYSHCCIDLN;
    private String SYSPATTN;
    private String SYOTIND;
    private String SYEXVAR0;
    private String SYEXVAR1;
    private String SYEXVAR4;
    private String SYEXVAR5;
    private String SYEXVAR6;
    private String SYEXVAR7;
    private String SYEXVAR12;
    private String SYEXVAR13;
    private String SYEXNM0;
    private String SYEXNM1;
    private String SYEXNM2;
    private String SYEXNMP0;
    private String SYEXNMP1;
    private String SYEXNMP2;
    private String SYEXDT0;
    private String SYEXDT1;
    private String SYEXDT2;
    private String SYPOHP01;
    private String SYPOHP02;
    private String SYPOHP03;
    private String SYPOHP04;
    private String SYPOHP05;
    private String SYPOHP06;
    private String SYPOHP07;
    private String SYPOHP08;
    private String SYPOHP09;
    private String SYPOHP10;
    private String SYPOHP11;
    private String SYPOHP12;
    private String SYPOHC01;
    private String SYPOHC02;
    private String SYPOHC03;
    private String SYPOHC04;
    private String SYPOHC05;
    private String SYPOHC06;
    private String SYPOHC07;
    private String SYPOHC08;
    private String SYPOHC09;
    private String SYPOHC10;
    private String SYPOHC11;
    private String SYPOHC12;
    private String SYPOHD01;
    private String SYPOHD02;
    private String SYPOHAB01;
    private String SYPOHAB02;
    private String SYPOHP13;
    private String SYPOHU01;
    private String SYPOHU02;
    private String SYRETI;
    private String SYCLASS01;
    private String SYCLASS02;
    private String SYCLASS03;
    private String SYCLASS04;
    private String SYCLASS05;
    private String SYGAN8;
    private String SYGSHAN;
    private String SYGPA8;
    private String SYGCARS;
    private String SYGPBAN;
    private String SYGITAN;
    private String SYGFTAN;
    private String SYGDVAN;
    private String SYGPRAN8;
    private List<F47012_1> Detalle_F47012_1;
    private List<F47012_2> Detalle_F47012_2;
    private F4714 F4714;

    @Override
    public String toString() {
        return "F47011{" + "SYEDTY=" + SYEDTY + ", SYEDSQ=" + SYEDSQ + ", SYEKCO=" + SYEKCO + ", SYEDOC=" + SYEDOC + ", SYEDCT=" + SYEDCT + ", SYEDLN=" + SYEDLN + ", SYEDST=" + SYEDST + ", SYEDFT=" + SYEDFT + ", SYEDDT=" + SYEDDT + ", SYEDER=" + SYEDER + ", SYEDDL=" + SYEDDL + ", SYEDSP=" + SYEDSP + ", SYEDBT=" + SYEDBT + ", SYPNID=" + SYPNID + ", SYOFRQ=" + SYOFRQ + ", SYNXDJ=" + SYNXDJ + ", SYSSDJ=" + SYSSDJ + ", SYTPUR=" + SYTPUR + ", SYKCOO=" + SYKCOO + ", SYDOCO=" + SYDOCO + ", SYDCTO=" + SYDCTO + ", SYSFXO=" + SYSFXO + ", SYMCU=" + SYMCU + ", SYCO=" + SYCO + ", SYOKCO=" + SYOKCO + ", SYOORN=" + SYOORN + ", SYOCTO=" + SYOCTO + ", SYRKCO=" + SYRKCO + ", SYRORN=" + SYRORN + ", SYRCTO=" + SYRCTO + ", SYAN8=" + SYAN8 + ", SYSHAN=" + SYSHAN + ", SYPA8=" + SYPA8 + ", SYDRQJ=" + SYDRQJ + ", SYTRDJ=" + SYTRDJ + ", SYPDDJ=" + SYPDDJ + ", SYOPDJ=" + SYOPDJ + ", SYADDJ=" + SYADDJ + ", SYCNDJ=" + SYCNDJ + ", SYPEFJ=" + SYPEFJ + ", SYPPDJ=" + SYPPDJ + ", SYPSDJ=" + SYPSDJ + ", SYVR01=" + SYVR01 + ", SYVR02=" + SYVR02 + ", SYDEL1=" + SYDEL1 + ", SYDEL2=" + SYDEL2 + ", SYINMG=" + SYINMG + ", SYPTC=" + SYPTC + ", SYRYIN=" + SYRYIN + ", SYASN=" + SYASN + ", SYPRGP=" + SYPRGP + ", SYTRDC=" + SYTRDC + ", SYPCRT=" + SYPCRT + ", SYTXA1=" + SYTXA1 + ", SYEXR1=" + SYEXR1 + ", SYTXCT=" + SYTXCT + ", SYATXT=" + SYATXT + ", SYPRIO=" + SYPRIO + ", SYBACK=" + SYBACK + ", SYSBAL=" + SYSBAL + ", SYNTR=" + SYNTR + ", SYANBY=" + SYANBY + ", SYCARS=" + SYCARS + ", SYMOT=" + SYMOT + ", SYCOT=" + SYCOT + ", SYROUT=" + SYROUT + ", SYSTOP=" + SYSTOP + ", SYZON=" + SYZON + ", SYCNID=" + SYCNID + ", SYFRTH=" + SYFRTH + ", SYAFT=" + SYAFT + ", SYRCD=" + SYRCD + ", SYOTOT=" + SYOTOT + ", SYTOTC=" + SYTOTC + ", SYWUMD=" + SYWUMD + ", SYVUMD=" + SYVUMD + ", SYAUTN=" + SYAUTN + ", SYCACT=" + SYCACT + ", SYCEXP=" + SYCEXP + ", SYCRMD=" + SYCRMD + ", SYCRRM=" + SYCRRM + ", SYCRCD=" + SYCRCD + ", SYCRR=" + SYCRR + ", SYLNGP=" + SYLNGP + ", SYFAP=" + SYFAP + ", SYFCST=" + SYFCST + ", SYORBY=" + SYORBY + ", SYTKBY=" + SYTKBY + ", SYURCD=" + SYURCD + ", SYURDT=" + SYURDT + ", SYURAT=" + SYURAT + ", SYURAB=" + SYURAB + ", SYURRF=" + SYURRF + ", SYTORG=" + SYTORG + ", SYUSER=" + SYUSER + ", SYPID=" + SYPID + ", SYJOBN=" + SYJOBN + ", SYUPMJ=" + SYUPMJ + ", SYTDAY=" + SYTDAY + ", SYIR01=" + SYIR01 + ", SYIR02=" + SYIR02 + ", SYIR03=" + SYIR03 + ", SYIR04=" + SYIR04 + ", SYIR05=" + SYIR05 + ", SYVR03=" + SYVR03 + ", SYSOOR=" + SYSOOR + ", SYPMDT=" + SYPMDT + ", SYRSDT=" + SYRSDT + ", SYRQSJ=" + SYRQSJ + ", SYPSTM=" + SYPSTM + ", SYPDTT=" + SYPDTT + ", SYOPTT=" + SYOPTT + ", SYDRQT=" + SYDRQT + ", SYADTM=" + SYADTM + ", SYADLJ=" + SYADLJ + ", SYPBAN=" + SYPBAN + ", SYITAN=" + SYITAN + ", SYFTAN=" + SYFTAN + ", SYDVAN=" + SYDVAN + ", SYDOC1=" + SYDOC1 + ", SYDCT4=" + SYDCT4 + ", SYCORD=" + SYCORD + ", SYBSC=" + SYBSC + ", SYBCRC=" + SYBCRC + ", SYRSHT=" + SYRSHT + ", SYHOLD=" + SYHOLD + ", SYFUF1=" + SYFUF1 + ", SYAUFT=" + SYAUFT + ", SYAUFI=" + SYAUFI + ", SYOPBO=" + SYOPBO + ", SYOPTC=" + SYOPTC + ", SYOPLD=" + SYOPLD + ", SYOPBK=" + SYOPBK + ", SYOPSB=" + SYOPSB + ", SYOPPS=" + SYOPPS + ", SYOPPL=" + SYOPPL + ", SYOPMS=" + SYOPMS + ", SYOPSS=" + SYOPSS + ", SYOPBA=" + SYOPBA + ", SYOPLL=" + SYOPLL + ", SYPRAN8=" + SYPRAN8 + ", SYPRCIDLN=" + SYPRCIDLN + ", SYOPPID=" + SYOPPID + ", SYCCIDLN=" + SYCCIDLN + ", SYSDATTN=" + SYSDATTN + ", SYSHCCIDLN=" + SYSHCCIDLN + ", SYSPATTN=" + SYSPATTN + ", SYOTIND=" + SYOTIND + ", SYEXVAR0=" + SYEXVAR0 + ", SYEXVAR1=" + SYEXVAR1 + ", SYEXVAR4=" + SYEXVAR4 + ", SYEXVAR5=" + SYEXVAR5 + ", SYEXVAR6=" + SYEXVAR6 + ", SYEXVAR7=" + SYEXVAR7 + ", SYEXVAR12=" + SYEXVAR12 + ", SYEXVAR13=" + SYEXVAR13 + ", SYEXNM0=" + SYEXNM0 + ", SYEXNM1=" + SYEXNM1 + ", SYEXNM2=" + SYEXNM2 + ", SYEXNMP0=" + SYEXNMP0 + ", SYEXNMP1=" + SYEXNMP1 + ", SYEXNMP2=" + SYEXNMP2 + ", SYEXDT0=" + SYEXDT0 + ", SYEXDT1=" + SYEXDT1 + ", SYEXDT2=" + SYEXDT2 + ", SYPOHP01=" + SYPOHP01 + ", SYPOHP02=" + SYPOHP02 + ", SYPOHP03=" + SYPOHP03 + ", SYPOHP04=" + SYPOHP04 + ", SYPOHP05=" + SYPOHP05 + ", SYPOHP06=" + SYPOHP06 + ", SYPOHP07=" + SYPOHP07 + ", SYPOHP08=" + SYPOHP08 + ", SYPOHP09=" + SYPOHP09 + ", SYPOHP10=" + SYPOHP10 + ", SYPOHP11=" + SYPOHP11 + ", SYPOHP12=" + SYPOHP12 + ", SYPOHC01=" + SYPOHC01 + ", SYPOHC02=" + SYPOHC02 + ", SYPOHC03=" + SYPOHC03 + ", SYPOHC04=" + SYPOHC04 + ", SYPOHC05=" + SYPOHC05 + ", SYPOHC06=" + SYPOHC06 + ", SYPOHC07=" + SYPOHC07 + ", SYPOHC08=" + SYPOHC08 + ", SYPOHC09=" + SYPOHC09 + ", SYPOHC10=" + SYPOHC10 + ", SYPOHC11=" + SYPOHC11 + ", SYPOHC12=" + SYPOHC12 + ", SYPOHD01=" + SYPOHD01 + ", SYPOHD02=" + SYPOHD02 + ", SYPOHAB01=" + SYPOHAB01 + ", SYPOHAB02=" + SYPOHAB02 + ", SYPOHP13=" + SYPOHP13 + ", SYPOHU01=" + SYPOHU01 + ", SYPOHU02=" + SYPOHU02 + ", SYRETI=" + SYRETI + ", SYCLASS01=" + SYCLASS01 + ", SYCLASS02=" + SYCLASS02 + ", SYCLASS03=" + SYCLASS03 + ", SYCLASS04=" + SYCLASS04 + ", SYCLASS05=" + SYCLASS05 + ", SYGAN8=" + SYGAN8 + ", SYGSHAN=" + SYGSHAN + ", SYGPA8=" + SYGPA8 + ", SYGCARS=" + SYGCARS + ", SYGPBAN=" + SYGPBAN + ", SYGITAN=" + SYGITAN + ", SYGFTAN=" + SYGFTAN + ", SYGDVAN=" + SYGDVAN + ", SYGPRAN8=" + SYGPRAN8 + ", Detalle_F47012_1=" + Detalle_F47012_1 + ", Detalle_F47012_2=" + Detalle_F47012_2 + ", F4714=" + F4714 + '}';
    }
    
}
